Feature/8165 8166
bcgov/namex pull request #1146
Opened 2021-07-23 14:27 UTC by vysakh-menon-aot

*Issue:* bcgov/entity#8165, bcgov/entity#8166

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

2021-07-26 16:03 UTC, andrepestana-aot requested changes

2021-07-26 16:03 UTC, andrepestana-aot commented on services/namex-pay/src/namex_pay/worker.py
> +                            )
In https://github.com/bcgov/namex/pull/1142 I created a queue_util function to build the payload. If PR 1142 is merged before you could use it too.

2021-07-26 16:07 UTC, vysakh-menon-aot commented on api/namex/resources/name_requests/abstract_nr_resource.py
> +            msg_type='bc.registry.names.request',
this is the one used in entity emailer

2021-08-03 16:42 UTC, thorwolpert approved these changes

2021-08-04 06:11 UTC, merged