5687 stem distinctive
bcgov/namex pull request #941
Opened 2020-11-25 05:02 UTC by areyeslo

*bcgov/entity#5687:*

*Description of changes:*
- Stemming distinctives and descriptives in dictionaries
- Search in synonyms for original word, if no result stemming word
- Adding gerund form for distinctives
- Deleted additional_dist_desc function, it is not longer needed after name examination session with Genevieve.
- Added test cases.

Regression Test:
![image](https://user-images.githubusercontent.com/10526131/100185207-24aa9d80-2e98-11eb-9e48-5d558bcdf5ca.png)

Test 1 (plurals):
![image](https://user-images.githubusercontent.com/10526131/100185222-2d02d880-2e98-11eb-8ced-108c1222fb75.png)

Test 2 (original distinctive - Mechanical in the same category as plumbing):
![image](https://user-images.githubusercontent.com/10526131/100185234-33915000-2e98-11eb-9831-e9182f619341.png)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

2020-11-25 17:52 UTC, vysakh-menon-aot approved these changes

2020-11-26 21:00 UTC, vysakh-menon-aot approved these changes

2020-11-26 22:20 UTC, kialj876 approved these changes

2020-11-26 22:22 UTC, kialj876 requested changes
hey arturo can you fix the build? Looks like it's failing the GHA build due to the dataclasses version? ```dataclasses==0.8``` in requirements.txt should be something else I guess. I don't think you altered this but can you change it to whatever version you have running locally?

Other than that looks very good

2020-11-26 23:06 UTC, merged